### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by Drswith** [slightc/luatos_esp32_pio#1]
报错提示 *** [.pio\build\esp32\.pio\build\esp32\x509_crt_bundle.o] Source `.pio\build\esp32\x509_crt_bundle.S' not found, needed by target `.pio\build\esp32\.pio\build\esp32\x509_crt_bundle.o'.
请问是缺失了什么文件吗？
是不是luatos的mbedtls加密库？

**Comment by slightc** [comment]
是不是pio里的idf framework版本比较低

**Comment by Drswith** [comment]
查看了安装的 C:\Users\drs\.platformio\packages\framework-espidf\version.txt
版本是4.3.0。。不低了吧

**Comment by slightc** [comment]
我在macos编译测试ok 我换win试一下

**Comment by Drswith** [comment]
完整的log如下
> Executing task: C:\Users\drs\.platformio\penv\Scripts\platformio.exe run <

Processing esp32 (platform: espressif32; board: featheresp32; framework: espidf)
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/featheresp32.html
PLATFORM: Espressif 32 (3.3.2) > Adafruit ESP32 Feather
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
DEBUG: Current (esp-prog) External (esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES:
 - framework-espidf 3.40300.0 (4.3.0)
 - tool-cmake 3.16.4
 - tool-esptoolpy 1.30100.210531 (3.1.0)
 - tool-idf 1.0.1
 - tool-mconf 1.4060000.20190628 (406.0.0)
 - tool-ninja 1.9.0
 - toolchain-esp32ulp 1.22851.191205 (2.28.51)
 - toolchain-xtensa32 2.80400.210211 (8.4.0)
Reading CMake configuration...
Generating assembly for certificate bundle...
CMake Error at C:/Users/drs/.platformio/packages/framework-espidf/tools/cmake/scripts/data_file_embed_asm.cmake:26 (file):
  file failed to open for reading (No such file or directory):

    C:\Users\drs\Desktop\luatos_esp32_pio\.pio\build\esp32\x509_crt_bundle


*** Error 1
LDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 0 compatible libraries
Scanning dependencies...
No dependencies
Building in debug mode
*** [.pio\build\esp32\.pio\build\esp32\x509_crt_bundle.o] Source `.pio\build\esp32\x509_crt_bundle.S' not found, needed by target `.pio\build\esp32\.pio\build\esp32\x509_crt_bundle.o'.
============================================================================================================== [FAILED] Took 12.73 seconds ==============================================================================================================
终端进程“C:\Users\drs\.platformio\penv\Scripts\platformio.exe 'run'”已终止，退出代码: 1。

终端将被任务重用，按任意键关闭。

**Comment by slightc** [comment]
CERTIFICATE_BUNDLE配置问题 已更新代码
